In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
from google.colab import files
uploaded = files.upload()
a=next(iter(uploaded))

Saving winequality-red.csv to winequality-red (1).csv

In [5]:
df = pd.read_csv(a)

In [6]:
df.head(10)

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
5,7.4,0.66,0.00,1.8,0.075,13.0,40.0,0.9978,3.51,0.56,9.4,5
6,7.9,0.60,0.06,1.6,0.069,15.0,59.0,0.9964,3.30,0.46,9.4,5
7,7.3,0.65,0.00,1.2,0.065,15.0,21.0,0.9946,3.39,0.47,10.0,7
8,7.8,0.58,0.02,2.0,0.073,9.0,18.0,0.9968,3.36,0.57,9.5,7
9,7.5,0.50,0.36,6.1,0.071,17.0,102.0,0.9978,3.35,0.80,10.5,5

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [8]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df.drop_duplicates(inplace=True)

In [10]:
X = df.drop('quality', axis=1)
y = df['quality']

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [28]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, f1_score

model = SVC(kernel='rbf', C=2, class_weight='balanced',gamma='scale')


model.fit(X_train_scaled, y_train)
y_pred = model.predict(X_test_scaled)

Accuracy_score = accuracy_score(y_test, y_pred)
score_f1 = f1_score(y_test, y_pred, average='weighted')

print("Accuracy:", Accuracy_score)
print("F1:", score_f1)

Accuracy: 0.5036764705882353
F1: 0.5295419920777114

In [27]:
noise_levels = [0, 0.01, 0.05, 0.1, 0.2, 0.3,0.4,0.5]

for noise in noise_levels:

    X_train_noise = X_train_scaled + noise * np.random.randn(*X_train.shape)
    X_test_noise  = X_test_scaled  + noise * np.random.randn(*X_test.shape)

    model = SVC(kernel='rbf', C=2, class_weight='balanced',gamma='scale')

    model.fit(X_train_noise, y_train)

    y_pred = model.predict(X_test_noise)

    print("Noise:", noise,
          "Accuracy:", accuracy_score(y_test, y_pred))

Noise: 0 Accuracy: 0.5036764705882353
Noise: 0.01 Accuracy: 0.5110294117647058
Noise: 0.05 Accuracy: 0.5036764705882353
Noise: 0.1 Accuracy: 0.5
Noise: 0.2 Accuracy: 0.5073529411764706
Noise: 0.3 Accuracy: 0.5294117647058824
Noise: 0.4 Accuracy: 0.5257352941176471
Noise: 0.5 Accuracy: 0.4889705882352941

In [24]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

param_grid = {
    'C': [0.01, 0.1, 1, 10, 100],
    'gamma': ['scale', 0.01, 0.1, 1]
}

grid = GridSearchCV(
    SVC(kernel='rbf'),
    param_grid,
    cv=5,
    scoring='f1_macro'
)

grid.fit(X_train_scaled, y_train)

print("Best C:", grid.best_params_)
print("Best CV Score:", grid.best_score_)


#This was an optional Code Cell,I just wanted to learn about hyperparameter tuning

Best C: {'C': 100, 'gamma': 'scale'}
Best CV Score: 0.2842006182361149